apiVersion: v1
kind: Service
metadata:
  name: careerpath-service
  namespace: saleproject
spec:
  selector:
    app: careerpath
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
  type: LoadBalancer
